volumes:
    db:

services:
  db:
    image: postgres:12
    networks:
      - postgres
    env_file:
      - .env/local/postgres
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data/pgdata

networks:
  postgres:
    driver: bridge
